apiVersion: v1
kind: Secret
metadata:
  name: k8s-config
  namespace: backstage
stringData:
  k8s-config.yaml: |
    type: 'config'
    clusters:
      - url: https://kubernetes.default.svc.cluster.local
        name: local
        authProvider: 'serviceAccount'
        skipTLSVerify: true
        skipMetricsLookup: true
        serviceAccountToken: 
          $file: /var/run/secrets/kubernetes.io/serviceaccount/token
        caData: 
          $file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
